language: python
python:
  - 3.4
  - 3.5
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install codecov
script: pytest test/main.py --cov=codecov
after_success:
  - codecov
